name: TicketsPlus
version: ${project.version}
main: com.ticketsplus.TicketsPlus
api-version: 1.13
authors: [Quokka]
description: The final Tickets plugin.

commands:
  ticket:

permissions:
  ticket.admin.*:
    children:
      - ticket.staff.*
      - ticket.notify
      - ticket.notifytoggle
      - ticket.debug
      - ticket.notify.all
      - ticket.forcedelete
      - ticket.claim.override
  ticket.staff.*:
    children:
      - ticket.player.*
      - ticket.notify
      - ticket.teleport
      - ticket.claim
      - ticket.comment
      - ticket.list
      - ticket.close
  ticket.player.*:
    children:
      - ticket.create
      - ticket.close.self
  ticket.notify.all:
    description: Recieve all ticket notifications.
  ticket.notify:
    description: Recieve ticket creation notifications.
  ticket.notifytoggle:
    description: Toggle notifications to be off.
  ticket.debug:
    description: Debug a ticket to check for faults.
  ticket.teleport:
    description: Teleport to a ticket location through GUI.
  ticket.claim:
    description: Claim a ticket for yourself!
  ticket.claim.override:
    description: Override the current assignee of a ticket.
  ticket.close.override:
    description: Close a ticket even if you aren't the assignee.
  ticket.comment:
    description: Leave a comment on a ticket.
  ticket.list:
    description: List all current tickets open.